# сравнение планшетов по ключевым характеристикам
tablets_compact = [
    {
        "model": "iPad Pro 12.9",
        "screen_size_in": 12.9,
        "resolution_px": "2732x2048",
        "ram_gb": 16,
        "storage_gb": 256,
        "battery_mah": 10758,
        "weight_g": 682,
        "stylus_support": True,
        "price_rub": 119990,
    },
    {
        "model": "Samsung Galaxy Tab S9 Ultra",
        "screen_size_in": 14.6,
        "resolution_px": "2960x1848",
        "ram_gb": 12,
        "storage_gb": 256,
        "battery_mah": 11200,
        "weight_g": 732,
        "stylus_support": True,
        "price_rub": 99990,
    },
    {
        "model": "Microsoft Surface Pro 9",
        "screen_size_in": 13.0,
        "resolution_px": "2880x1920",
        "ram_gb": 16,
        "storage_gb": 512,
        "battery_mah": 5070,
        "weight_g": 891,
        "stylus_support": True,
        "price_rub": 129990,
    },
    {
        "model": "Xiaomi Pad 6",
        "screen_size_in": 11.0,
        "resolution_px": "2880x1800",
        "ram_gb": 8,
        "storage_gb": 256,
        "battery_mah": 8840,
        "weight_g": 490,
        "stylus_support": False,
        "price_rub": 39990,
    },
]
